CreateConVar("inpc_enabled", 1, FCVAR_NOTIFY + FCVAR_ARCHIVE)
CreateConVar("inpc_debug", 0, FCVAR_CHEAT + FCVAR_PROTECTED)

CreateConVar("inpc_cleanup", 0, FCVAR_NOTIFY + FCVAR_ARCHIVE)

CreateConVar("inpc_weaponproficiency", 4, FCVAR_NOTIFY + FCVAR_ARCHIVE)
CreateConVar("inpc_nofriendlyfire", 1, FCVAR_NOTIFY + FCVAR_ARCHIVE)
CreateConVar("inpc_damage_invulnerable", 1, FCVAR_NOTIFY + FCVAR_ARCHIVE)
CreateConVar("inpc_unlimited_vision", 1, FCVAR_NOTIFY + FCVAR_ARCHIVE)
CreateConVar("inpc_patrol", 1, FCVAR_NOTIFY + FCVAR_ARCHIVE)
CreateConVar("inpc_custom_health", 1, FCVAR_NOTIFY + FCVAR_ARCHIVE)
CreateConVar("inpc_health_regeneration", 1, FCVAR_NOTIFY + FCVAR_ARCHIVE)
CreateConVar("inpc_enable_factions", 1, FCVAR_NOTIFY + FCVAR_ARCHIVE)
CreateConVar("inpc_allow_adding_npcs_to_squad", 1, FCVAR_NOTIFY + FCVAR_ARCHIVE)
CreateConVar("inpc_metropolice_manhacks", 1, FCVAR_NOTIFY + FCVAR_ARCHIVE)

CreateConVar("inpc_ai_infantry", 1, FCVAR_NOTIFY + FCVAR_ARCHIVE)
CreateConVar("inpc_ai_zombie", 1, FCVAR_NOTIFY + FCVAR_ARCHIVE)
CreateConVar("inpc_ai_fastzombie", 1, FCVAR_NOTIFY + FCVAR_ARCHIVE)
CreateConVar("inpc_ai_poisonzombie_disablethrowheadcrabs", 0, FCVAR_NOTIFY + FCVAR_ARCHIVE)
CreateConVar("inpc_ai_antlion", 1, FCVAR_NOTIFY + FCVAR_ARCHIVE)
CreateConVar("inpc_ai_antlion_worker", 1, FCVAR_NOTIFY + FCVAR_ARCHIVE)
CreateConVar("inpc_ai_antlion_guard", 1, FCVAR_NOTIFY + FCVAR_ARCHIVE)
CreateConVar("inpc_ai_antlion_guard_chargeacceleration", 1, FCVAR_NOTIFY + FCVAR_ARCHIVE)
CreateConVar("inpc_ai_hunter", 1, FCVAR_NOTIFY + FCVAR_ARCHIVE)
CreateConVar("inpc_ai_vortigaunt", 1, FCVAR_NOTIFY + FCVAR_ARCHIVE)
CreateConVar("inpc_ai_frenzy", 1, FCVAR_NOTIFY + FCVAR_ARCHIVE)

CreateConVar("inpc_custom_playermodel_faction", "resistance", FCVAR_NOTIFY + FCVAR_ARCHIVE)
CreateConVar("inpc_force_player_faction", "default", FCVAR_NOTIFY + FCVAR_ARCHIVE)

CreateConVar("inpc_forcefaction", "default", FCVAR_ARCHIVE + FCVAR_USERINFO)